In [2]:
import pandas as pd
df=pd.read_csv("wfp_food_prices_phl.csv", low_memory=False)

df

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
0,#date,#adm1+name,#adm2+name,#loc+market+name,#geo+lat,#geo+lon,#item+type,#item+name,#item+unit,#item+price+flag,#item+price+type,#currency,#value,#value+usd
1,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,Maize flour (yellow),KG,actual,Retail,PHP,15,0.3717
2,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (milled, superior)",KG,actual,Retail,PHP,20,0.4957
3,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (milled, superior)",KG,actual,Wholesale,PHP,18.35,0.4548
4,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (regular, milled)",KG,actual,Retail,PHP,18,0.4461
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107350,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Ginger,KG,aggregate,Retail,PHP,114,2.3725
107351,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Mangoes (carabao),KG,aggregate,Retail,PHP,106.67,2.2199
107352,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Onions (red),KG,aggregate,Retail,PHP,114.17,2.3759
107353,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Papaya,KG,aggregate,Retail,PHP,45,0.9365
107354,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Tomatoes,KG,aggregate,Retail,PHP,81.67,1.6996

In [3]:
df=df[1:][:]
df

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
1,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,Maize flour (yellow),KG,actual,Retail,PHP,15,0.3717
2,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (milled, superior)",KG,actual,Retail,PHP,20,0.4957
3,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (milled, superior)",KG,actual,Wholesale,PHP,18.35,0.4548
4,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (regular, milled)",KG,actual,Retail,PHP,18,0.4461
5,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (regular, milled)",KG,actual,Wholesale,PHP,16.35,0.4052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107350,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Ginger,KG,aggregate,Retail,PHP,114,2.3725
107351,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Mangoes (carabao),KG,aggregate,Retail,PHP,106.67,2.2199
107352,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Onions (red),KG,aggregate,Retail,PHP,114.17,2.3759
107353,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Papaya,KG,aggregate,Retail,PHP,45,0.9365
107354,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Tomatoes,KG,aggregate,Retail,PHP,81.67,1.6996

In [4]:
df=df.dropna()
df.reset_index(drop=True, inplace=True)
df.shape

(107354, 14)

In [5]:
df=df.drop(labels='usdprice',axis=1)
df=df.drop(labels='currency',axis=1)

In [6]:

df=df.drop(labels='pricetype',axis=1) 
df

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,price
0,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,Maize flour (yellow),KG,actual,15
1,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (milled, superior)",KG,actual,20
2,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (milled, superior)",KG,actual,18.35
3,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (regular, milled)",KG,actual,18
4,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (regular, milled)",KG,actual,16.35
...,...,...,...,...,...,...,...,...,...,...,...
107349,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Ginger,KG,aggregate,114
107350,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Mangoes (carabao),KG,aggregate,106.67
107351,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Onions (red),KG,aggregate,114.17
107352,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Papaya,KG,aggregate,45
107353,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Tomatoes,KG,aggregate,81.67

In [7]:
df=df.rename({'admin1': 'province', 'admin2': 'district'}, axis=1) 
df

,date,province,district,market,latitude,longitude,category,commodity,unit,priceflag,price
0,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,Maize flour (yellow),KG,actual,15
1,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (milled, superior)",KG,actual,20
2,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (milled, superior)",KG,actual,18.35
3,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (regular, milled)",KG,actual,18
4,2000-01-15,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (regular, milled)",KG,actual,16.35
...,...,...,...,...,...,...,...,...,...,...,...
107349,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Ginger,KG,aggregate,114
107350,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Mangoes (carabao),KG,aggregate,106.67
107351,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Onions (red),KG,aggregate,114.17
107352,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Papaya,KG,aggregate,45
107353,2021-02-15,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Tomatoes,KG,aggregate,81.67

In [8]:
import numpy as np

size=len(df['date'])
year_arr=np.zeros((size,1))
month_arr=np.zeros((size,1))
i=0
for date in df['date']:
  darr=date.split('-')
  year_arr[i]=darr[0]
  month_arr[i]=darr[1]
  #print(darr[1])
  i+=1

df['year']=year_arr.astype(int)
df['month']=month_arr.astype(int)
df=df.drop(labels='date',axis=1) 

df

,province,district,market,latitude,longitude,category,commodity,unit,priceflag,price,year,month
0,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,Maize flour (yellow),KG,actual,15,2000,1
1,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (milled, superior)",KG,actual,20,2000,1
2,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (milled, superior)",KG,actual,18.35,2000,1
3,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (regular, milled)",KG,actual,18,2000,1
4,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,cereals and tubers,"Rice (regular, milled)",KG,actual,16.35,2000,1
...,...,...,...,...,...,...,...,...,...,...,...,...
107349,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Ginger,KG,aggregate,114,2021,2
107350,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Mangoes (carabao),KG,aggregate,106.67,2021,2
107351,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Onions (red),KG,aggregate,114.17,2021,2
107352,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Papaya,KG,aggregate,45,2021,2
107353,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,vegetables and fruits,Tomatoes,KG,aggregate,81.67,2021,2

In [11]:
cats_uniq = df['category'].unique()
cats_uniq

array(['cereals and tubers', 'meat, fish and eggs',
       'vegetables and fruits', 'pulses and nuts', 'miscellaneous food',
       'oil and fats'], dtype=object)

In [12]:
dict_cats={}

for i in range (len(cats_uniq)):
    dict_cats[cats_uniq[i]] = i+1
dict_cats

{'cereals and tubers': 1,
 'meat, fish and eggs': 2,
 'vegetables and fruits': 3,
 'pulses and nuts': 4,
 'miscellaneous food': 5,
 'oil and fats': 6}

In [13]:
size=len(df['category'])
catg=df['category'].unique()

catgarr=list(dict_cats.keys())
carr=dict_cats
for i in range (len(catg)):
  a=np.zeros((size,1))
  exec('catgarr[i] = a')



for j in range (size):
  cval=df['category'][j]
  ind=carr.get(cval)
  catgarr[ind-1][j]=1

r=0
for c in catg:
  df[c]=catgarr[r].astype(int)
  r+=1

df=df.drop(labels='category',axis=1) 
df

,province,district,market,latitude,longitude,commodity,unit,priceflag,price,year,month,cereals and tubers,"meat, fish and eggs",vegetables and fruits,pulses and nuts,miscellaneous food,oil and fats
0,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,Maize flour (yellow),KG,actual,15,2000,1,1,0,0,0,0,0
1,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,"Rice (milled, superior)",KG,actual,20,2000,1,1,0,0,0,0,0
2,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,"Rice (milled, superior)",KG,actual,18.35,2000,1,1,0,0,0,0,0
3,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,"Rice (regular, milled)",KG,actual,18,2000,1,1,0,0,0,0,0
4,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,"Rice (regular, milled)",KG,actual,16.35,2000,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107349,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,Ginger,KG,aggregate,114,2021,2,0,0,1,0,0,0
107350,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,Mangoes (carabao),KG,aggregate,106.67,2021,2,0,0,1,0,0,0
107351,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,Onions (red),KG,aggregate,114.17,2021,2,0,0,1,0,0,0
107352,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,Papaya,KG,aggregate,45,2021,2,0,0,1,0,0,0
107353,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,Tomatoes,KG,aggregate,81.67,2021,2,0,0,1,0,0,0

In [14]:
df['year'] = df['year'].apply(str)

In [15]:
year_uniq = df['year'].unique()
year_uniq

array(['2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021', '2022'],
      dtype=object)

In [17]:
dict_years={}

for i in range (len(year_uniq)):
    dict_years[year_uniq[i]] = i+1
dict_years

{'2000': 1,
 '2001': 2,
 '2002': 3,
 '2003': 4,
 '2004': 5,
 '2005': 6,
 '2006': 7,
 '2007': 8,
 '2008': 9,
 '2009': 10,
 '2010': 11,
 '2011': 12,
 '2012': 13,
 '2013': 14,
 '2014': 15,
 '2015': 16,
 '2016': 17,
 '2017': 18,
 '2018': 19,
 '2019': 20,
 '2020': 21,
 '2021': 22,
 '2022': 23}

In [18]:
size=len(df['year'])
catg=df['year'].unique()

catgarr=list(dict_years.keys())
carr=dict_years
for i in range (len(catg)):
  a=np.zeros((size,1))
  exec('catgarr[i] = a')



for j in range (size):
  cval=df['year'][j]
  ind=carr.get(cval)
  catgarr[ind-1][j]=1

r=0
for c in catg:
  df[c]=catgarr[r].astype(int)
  r+=1

df=df.drop(labels='year',axis=1) 
df

,province,district,market,latitude,longitude,commodity,unit,priceflag,price,month,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,Maize flour (yellow),KG,actual,15,1,...,0,0,0,0,0,0,0,0,0,0
1,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,"Rice (milled, superior)",KG,actual,20,1,...,0,0,0,0,0,0,0,0,0,0
2,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,"Rice (milled, superior)",KG,actual,18.35,1,...,0,0,0,0,0,0,0,0,0,0
3,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,"Rice (regular, milled)",KG,actual,18,1,...,0,0,0,0,0,0,0,0,0,0
4,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,"Rice (regular, milled)",KG,actual,16.35,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107349,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,Ginger,KG,aggregate,114,2,...,0,0,0,0,0,0,0,0,1,0
107350,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,Mangoes (carabao),KG,aggregate,106.67,2,...,0,0,0,0,0,0,0,0,1,0
107351,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,Onions (red),KG,aggregate,114.17,2,...,0,0,0,0,0,0,0,0,1,0
107352,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,Papaya,KG,aggregate,45,2,...,0,0,0,0,0,0,0,0,1,0
107353,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,Tomatoes,KG,aggregate,81.67,2,...,0,0,0,0,0,0,0,0,1,0

In [19]:
com_uniq=df['commodity'].unique()

dict_comms={}

for i in range (len(com_uniq)):
    dict_comms[com_uniq[i]] = i+1
dict_comms

size=len(df['commodity'])
catg=df['commodity'].unique()

catgarr=list(dict_comms.keys())
carr=dict_comms
for i in range (len(catg)):
  a=np.zeros((size,1))
  exec('catgarr[i] = a')



for j in range (size):
  cval=df['commodity'][j]
  ind=carr.get(cval)
  catgarr[ind-1][j]=1

r=0
for c in catg:
  df[c]=catgarr[r].astype(int)
  r+=1

df=df.drop(labels='commodity',axis=1) 
df

,province,district,market,latitude,longitude,unit,priceflag,price,month,cereals and tubers,...,Mangoes (piko),Pineapples,Chicken,Mandarins,Sugar (brown),Sugar (white),Oil (cooking),Garlic (large),"Meat (pork, with fat)",Garlic (small)
0,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,actual,15,1,1,...,0,0,0,0,0,0,0,0,0,0
1,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,actual,20,1,1,...,0,0,0,0,0,0,0,0,0,0
2,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,actual,18.35,1,1,...,0,0,0,0,0,0,0,0,0,0
3,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,actual,18,1,1,...,0,0,0,0,0,0,0,0,0,0
4,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,actual,16.35,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107349,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,KG,aggregate,114,2,0,...,0,0,0,0,0,0,0,0,0,0
107350,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,KG,aggregate,106.67,2,0,...,0,0,0,0,0,0,0,0,0,0
107351,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,KG,aggregate,114.17,2,0,...,0,0,0,0,0,0,0,0,0,0
107352,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,KG,aggregate,45,2,0,...,0,0,0,0,0,0,0,0,0,0
107353,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,KG,aggregate,81.67,2,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
pf_uniq=df['priceflag'].unique()
pf_uniq

dict_pf={}

for i in range (len(pf_uniq)):
    dict_pf[pf_uniq[i]] = i+1
dict_pf

size=len(df['priceflag'])
catg=df['priceflag'].unique()

catgarr=list(dict_pf.keys())
carr=dict_pf
for i in range (len(catg)):
  a=np.zeros((size,1))
  exec('catgarr[i] = a')



for j in range (size):
  cval=df['priceflag'][j]
  ind=carr.get(cval)
  catgarr[ind-1][j]=1

r=0
for c in catg:
  df[c]=catgarr[r].astype(int)
  r+=1

df=df.drop(labels='priceflag',axis=1) 
df

,province,district,market,latitude,longitude,unit,price,month,cereals and tubers,"meat, fish and eggs",...,Mandarins,Sugar (brown),Sugar (white),Oil (cooking),Garlic (large),"Meat (pork, with fat)",Garlic (small),actual,"actual,aggregate",aggregate
0,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,15,1,1,0,...,0,0,0,0,0,0,0,1,0,0
1,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,20,1,1,0,...,0,0,0,0,0,0,0,1,0,0
2,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,18.35,1,1,0,...,0,0,0,0,0,0,0,1,0,0
3,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,18,1,1,0,...,0,0,0,0,0,0,0,1,0,0
4,National Capital region,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,16.35,1,1,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107349,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,KG,114,2,0,0,...,0,0,0,0,0,0,0,0,0,1
107350,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,KG,106.67,2,0,0,...,0,0,0,0,0,0,0,0,0,1
107351,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,KG,114.17,2,0,0,...,0,0,0,0,0,0,0,0,0,1
107352,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,KG,45,2,0,0,...,0,0,0,0,0,0,0,0,0,1
107353,Region XIII,Agusan del Norte,Butuan City,8.957268,125.534029,KG,81.67,2,0,0,...,0,0,0,0,0,0,0,0,0,1

In [21]:
prov_uniq=df['province'].unique()
prov_uniq

dict_prov={}

for i in range (len(prov_uniq)):
    dict_prov[prov_uniq[i]] = i+1
dict_prov

size=len(df['province'])
catg=df['province'].unique()

catgarr=list(dict_prov.keys())
carr=dict_prov
for i in range (len(catg)):
  a=np.zeros((size,1))
  exec('catgarr[i] = a')



for j in range (size):
  cval=df['province'][j]
  ind=carr.get(cval)
  catgarr[ind-1][j]=1

r=0
for c in catg:
  df[c]=catgarr[r].astype(int)
  r+=1

df=df.drop(labels='province',axis=1) 
df

,district,market,latitude,longitude,unit,price,month,cereals and tubers,"meat, fish and eggs",vegetables and fruits,...,Autonomous region in Muslim Mindanao,Cordillera Administrative region,Region I,Region II,Region IV-A,Region IV-B,Region V,Region VIII,Region X,Region XIII
0,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,15,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,20,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,18.35,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,18,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Metropolitan Manila,Metro Manila,14.604167,120.982222,KG,16.35,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107349,Agusan del Norte,Butuan City,8.957268,125.534029,KG,114,2,0,0,1,...,0,0,0,0,0,0,0,0,0,1
107350,Agusan del Norte,Butuan City,8.957268,125.534029,KG,106.67,2,0,0,1,...,0,0,0,0,0,0,0,0,0,1
107351,Agusan del Norte,Butuan City,8.957268,125.534029,KG,114.17,2,0,0,1,...,0,0,0,0,0,0,0,0,0,1
107352,Agusan del Norte,Butuan City,8.957268,125.534029,KG,45,2,0,0,1,...,0,0,0,0,0,0,0,0,0,1
107353,Agusan del Norte,Butuan City,8.957268,125.534029,KG,81.67,2,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [22]:
dist_uniq=df['district'].unique()
dist_uniq

dict_dist={}

for i in range (len(dist_uniq)):
    dict_dist[dist_uniq[i]] = i+1
dict_dist


size=len(df['district'])
catg=df['district'].unique()

catgarr=list(dict_dist.keys())
carr=dict_dist
for i in range (len(catg)):
  a=np.zeros((size,1))
  exec('catgarr[i] = a')



for j in range (size):
  cval=df['district'][j]
  ind=carr.get(cval)
  catgarr[ind-1][j]=1

r=0
for c in catg:
  df[c]=catgarr[r].astype(int)
  r+=1

df=df.drop(labels='district',axis=1) 
df

,market,latitude,longitude,unit,price,month,cereals and tubers,"meat, fish and eggs",vegetables and fruits,pulses and nuts,...,Davao del Norte,North Cotabato,Sarangani,Sultan Kudarat,Agusan del Norte,Agusan del Sur,Surigao del Norte,Lanao del Sur,Dinagat Islands,Camarines Sur
0,Metro Manila,14.604167,120.982222,KG,15,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Metro Manila,14.604167,120.982222,KG,20,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Metro Manila,14.604167,120.982222,KG,18.35,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Metro Manila,14.604167,120.982222,KG,18,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Metro Manila,14.604167,120.982222,KG,16.35,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107349,Butuan City,8.957268,125.534029,KG,114,2,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
107350,Butuan City,8.957268,125.534029,KG,106.67,2,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
107351,Butuan City,8.957268,125.534029,KG,114.17,2,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
107352,Butuan City,8.957268,125.534029,KG,45,2,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
107353,Butuan City,8.957268,125.534029,KG,81.67,2,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0

In [23]:
mrkt_uniq=df['market'].unique()
mrkt_uniq

dict_mrkt={}

for i in range (len(mrkt_uniq)):
    dict_mrkt[mrkt_uniq[i]] = i+1
dict_mrkt

size=len(df['market'])
catg=df['market'].unique()

catgarr=list(dict_mrkt.keys())
carr=dict_mrkt
for i in range (len(catg)):
  a=np.zeros((size,1))
  exec('catgarr[i] = a')



for j in range (size):
  cval=df['market'][j]
  ind=carr.get(cval)
  catgarr[ind-1][j]=1

r=0
for c in catg:
  df[c]=catgarr[r].astype(int)
  r+=1

df=df.drop(labels='market',axis=1) 
df

C:\Users\airco\AppData\Local\Temp\ipykernel_23900\3334658683.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[c]=catgarr[r].astype(int)
C:\Users\airco\AppData\Local\Temp\ipykernel_23900\3334658683.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[c]=catgarr[r].astype(int)
C:\Users\airco\AppData\Local\Temp\ipykernel_23900\3334658683.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[c]=catgarr[r].astype(int)
C:\Users\airco\AppData\Local\Temp\ipykernel_23900\3334658683.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[c]=catgarr[r].astype(int)
C:\Users\airco\AppData\Local\Temp\ipykernel_23900\3334658683.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[c]=catgarr[r].astype(int)
C:\Users\airco\AppData\Local\Temp\ipykernel_23900\3334658683.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[c]=catgarr[r].astype(int)
C:\Users\airco\AppData\Local\Temp\ipykernel_23900\3334658683.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[c]=catgarr[r].astype(int)
C:\Users\airco\AppData\Local\Temp\ipykernel_23900\3334658683.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[c]=catgarr[r].astype(int)
C:\Users\airco\AppData\Local\Temp\ipykernel_23900\3334658683.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[c]=catgarr[r].astype(int)
C:\Users\airco\AppData\Local\Temp\ipykernel_23900\3334658683.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[c]=catgarr[r].astype(int)

,latitude,longitude,unit,price,month,cereals and tubers,"meat, fish and eggs",vegetables and fruits,pulses and nuts,miscellaneous food,...,Baguio City,San Fernando City,Cabanatuan City,Batangas City,Naga City,Tacloban City,Cagayan de Oro City,Kidapawan City,Butuan City,Calapan City
0,14.604167,120.982222,KG,15,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,14.604167,120.982222,KG,20,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,14.604167,120.982222,KG,18.35,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,14.604167,120.982222,KG,18,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,14.604167,120.982222,KG,16.35,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107349,8.957268,125.534029,KG,114,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
107350,8.957268,125.534029,KG,106.67,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
107351,8.957268,125.534029,KG,114.17,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
107352,8.957268,125.534029,KG,45,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
107353,8.957268,125.534029,KG,81.67,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0

In [24]:
df['month'] = df['month'].apply(str)

month_uniq=df['month'].unique()
month_uniq

m_uniq=[]

for i in range (len(month_uniq)):
    m_uniq.append("m" + month_uniq[i])
m_uniq

['m1', 'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9', 'm10', 'm11', 'm12']

In [25]:

for i in range (len(month_uniq)):
    df['month'] = df['month'].replace(month_uniq[i],m_uniq[i])
df

dict_month={}

for i in range (len(month_uniq)):
    monthnum= "m" + month_uniq[i]
    dict_month[monthnum] = i+1
dict_month

size=len(df['month'])
catg=df['month'].unique()

catgarr=list(dict_month.keys())
carr=dict_month
for i in range (len(catg)):
  a=np.zeros((size,1))
  exec('catgarr[i] = a')



for j in range (size):
  cval=df['month'][j]
  ind=carr.get(cval)
  catgarr[ind-1][j]=1

r=0
for c in catg:
  df[c]=catgarr[r].astype(int)
  r+=1

df=df.drop(labels='month',axis=1) 
df

,latitude,longitude,unit,price,cereals and tubers,"meat, fish and eggs",vegetables and fruits,pulses and nuts,miscellaneous food,oil and fats,...,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12
0,14.604167,120.982222,KG,15,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,14.604167,120.982222,KG,20,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,14.604167,120.982222,KG,18.35,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,14.604167,120.982222,KG,18,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,14.604167,120.982222,KG,16.35,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107349,8.957268,125.534029,KG,114,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
107350,8.957268,125.534029,KG,106.67,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
107351,8.957268,125.534029,KG,114.17,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
107352,8.957268,125.534029,KG,45,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
107353,8.957268,125.534029,KG,81.67,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
unit_uniq=df['unit'].unique()
unit_uniq

dict_unit={}

for i in range (len(unit_uniq)):
    dict_unit[unit_uniq[i]] = i+1
dict_unit

size=len(df['unit'])
catg=df['unit'].unique()

catgarr=list(dict_unit.keys())
carr=dict_unit
for i in range (len(catg)):
  a=np.zeros((size,1))
  exec('catgarr[i] = a')



for j in range (size):
  cval=df['unit'][j]
  ind=carr.get(cval)
  catgarr[ind-1][j]=1

r=0
for c in catg:
  df[c]=catgarr[r].astype(int)
  r+=1

df=df.drop(labels='unit',axis=1) 
df

,latitude,longitude,price,cereals and tubers,"meat, fish and eggs",vegetables and fruits,pulses and nuts,miscellaneous food,oil and fats,2000,...,m6,m7,m8,m9,m10,m11,m12,KG,Unit,750 ML
0,14.604167,120.982222,15,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,14.604167,120.982222,20,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2,14.604167,120.982222,18.35,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,14.604167,120.982222,18,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4,14.604167,120.982222,16.35,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107349,8.957268,125.534029,114,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
107350,8.957268,125.534029,106.67,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
107351,8.957268,125.534029,114.17,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
107352,8.957268,125.534029,45,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
107353,8.957268,125.534029,81.67,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [27]:
df.to_csv("foodprice_processed_ph_1.csv",index=False)